### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by lukemelas** [orsic/swiftnet#1]
Hello authors, 

Thank you for your paper and for releasing pretrained models! I very much enjoyed reading your work. 

Would it be possible for you to release code to train the model from scratch / ImageNet weights?

**Comment by orsic** [comment]
@lukemelas thank you for your interest in our work.
We plan to extend the work from the paper and then release the training code and new models.

**Comment by lukemelas** [comment]
Sounds good! Looking forward to it.
