### ISSUE TITLE
Precision and recall error

### ISSUE THREAD

**Issue by sixtedemaupeou** [orsic/swiftnet#11]
Hello,

While conducting some adversarial attacks on this model with different objectives such as decreasing the recall or the precision specifically, I noticed that the values for mean class recall and mean class precision seemed to have been swapped.

I believe this is due to setting TPFP as what should be TPFN and vice versa in:
https://github.com/orsic/swiftnet/blob/92bed697c216ef5b7c296bd3307d6c70446db3ff/evaluation/evaluate.py#L18-L19

**Comment by orsic** [comment]
Thank you for this insight, I will look into it.
