### ISSUE TITLE
How to counting GFLOPs?

### ISSUE THREAD

**Issue by qqwwee1231** [orsic/swiftnet#12]
Really nice work.  Could you also share how do you count the GFLOPs? 
I used the 'Torchstat' and the tool shows the number of GFLOPs is actually twice the reported one.

**Comment by orsic** [comment]
Thank you for the interest. We count the number of FLOPs using the following [](https://github.com/xilaili/CondenseNet/blob/master/utils.py).
Which number of GFLOPs reported in the paper are you failing to reproduce? Which input resolution did you use?

**Comment by qqwwee1231** [comment]
> Thank you for the interest. We count the number of FLOPs using the following .
> Which number of GFLOPs reported in the paper are you failing to reproduce? Which input resolution did you use?

Oh, I mistake the GFLOPs and GFLOPs@1Mpx. The number is aligned actually. 
Thanks. Looking forward to seeing your training code.
