### ISSUE TITLE
Can not download the pretrained models

### ISSUE THREAD

**Issue by QTJiebin** [orsic/swiftnet#18]
Hi, I have tried to download the pretrained models, but I failed. So, is it convenient to provide other links, for example, Google Drive.

**Comment by theevann** [comment]
Having the same problem here. Could you provide a backup link please ?

**Comment by orsic** [comment]
@QTJiebin @theevann our web server is currently down. Thank you for the reminder.
In the meantime, you can download trained parameters from [Google Drive](https://drive.google.com/open?id=1DqX-N-nMtGG9QfMY_cKtULCKTfEuV4WT).

Thank you for the interest in our work!
