### ISSUE TITLE
How you obtain a SwiftNetRN-18 model with only 11.8M parameters?

### ISSUE THREAD

**Issue by BebDong** [orsic/swiftnet#22]
I am wondering how you obtain a SwiftNetRN-18 model with only 11.8M parameters? Even the most original ResNet-18 based FCN32s for Cityscapes dataset contains near 11.8M parameters. From the paper _In Defense of Pre-trained ImageNet Architectures for Real-time Semantic Segmentation of Road-driving Images_, we can see there are at least three extra 1x1 Convs and three 3x3 Convs, and even an SPP module.

Besides, with the U-shape structure, it's unlikely to gain speed of over 39 FPS with 2048x1024 input on a single GTX 1080Ti.

Would you please offer the skills too, except for only the codes to reproduce the mIoU, to get the speed and model compression performance?

**Comment by dxjundersky** [comment]
Only ResNet-18 is 42m?

**Comment by BebDong** [comment]
Excuse me?

**Comment by dxjundersky** [comment]
I remember that ResNet-18 has 4 layers with c=512 and k=3（one layer is 256 to 512).
So the last four layers's paramters are 512 * 512 * 3 * 3 * 4B(float32) * (1+1+1+0.5)  = 31.5M
31.5 * (1 + 1/4 + 1/16 + 1/64) = 41.8m
add bn and some other layers

**Comment by dxjundersky** [comment]
why 11.8M? (float8?)

**Comment by BebDong** [comment]
You may misunderstand what I was trying to say. By saying _with 11.8M parameters_, I mean the number of parameters instead of the memory consumption on the disk.

**Comment by dxjundersky** [comment]
Sorry...

**Comment by dxjundersky** [comment]
The ResNet-18 has about 10.6M，
 “ we can see there are at least three extra 1x1 Convs and three 3x3 Convs, and even an SPP module.” Their channels is small.

The biggest problem is that I don't know how to train.
I can only get 71.1% mIoU in 1024 * 2048.

**Comment by orsic** [comment]
@BebDong code for counting the models parameters is provided [here](https://github.com/orsic/swiftnet/blob/master/models/util.py#L9-L16).
Feel free to double check the reported number of parameters.
Pseudo code for measuring model inference speed is provided in the conference paper(Fig. 5)

@dxjundersky training code will be released before Dec 18th.

**Comment by BebDong** [comment]
@orsic Thank you very much!
