### ISSUE TITLE
dataset issues

### ISSUE THREAD

**Issue by yyfyan** [orsic/swiftnet#3]
Best job.
Now I have some problem:
(1)Camvid's resolution is 480x360 or 960x720 in the paper?
(2)original cityscape dataset has 1024x2048 resolution, how get 512x1024 resolution? resize the image?
(3)class balance weight is used in the paper?

**Comment by orsic** [comment]
@yyfyan thank you for your interest.
1) CamVid resolution is 960x720. The dataset can be downloaded from [here](http://mi.eng.cam.ac.uk/research/projects/VideoRec/CamSeq01/)
2) Yes, we resized the images using Pillow show by [this transformation](https://github.com/orsic/swiftnet/blob/master/data/transform.py#L113-L127)
3) We did not use class balancing to train our models.
