### ISSUE TITLE
Torch version

### ISSUE THREAD

**Issue by ToniRV** [orsic/swiftnet#5]
```
Could not find a version that satisfies the requirement torch==1.0.0a0+db5d313 (from -r requirements.txt (line 2)) (from versions: 0.1.2, 0.1.2.post1, 0.4.1, 0.4.1.post2, 1.0.0, 1.0.1, 1.0.1.post2)
No matching distribution found for torch==1.0.0a0+db5d313 (from -r requirements.txt (line 2))
```
Is it ok to use 1.0.0?

**Comment by orsic** [comment]
@ToniRV yes, everything should work on 1.0.0

**Comment by moonmyth** [comment]
@orsic ，when i run model，i meet a question:（import lib.cylib as cylib，ModuleNotFoundError: No module named 'lib.cylib'）,can u give some advise?

**Comment by hqabcxyxz** [comment]
> @orsic ，when i run model，i meet a question:（import lib.cylib as cylib，ModuleNotFoundError: No module named 'lib.cylib'）,can u give some advise?

Hi,do you fix  this problem? I get this error message too... If u have fix this problem, please give me some advise.

**Comment by orsic** [comment]
@moonmyth @hqabcxyxz inside the `lib/` directory, run the `build.sh` script to build the Cython module used for evaluation.

**Comment by YanaShpot** [comment]
To make it work needed to modify build.sh as follows:
> ! g++ -shared -pthread -fPIC -fwrapv -O3 -Wall -fno-strict-aliasing -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6 -o cylib.so cylib.cc
