### ISSUE TITLE
datasets tree structure

### ISSUE THREAD

**Issue by ToniRV** [orsic/swiftnet#6]
Would be great if you could specify that there is a structure on how cityscapes dataset is downloaded:
```
datasets/
├── gtFine
└── img
    └── left
        └── leftImg8bit
```

**Comment by orsic** [comment]
@ToniRV thanks, this is the default tree structure when unpacking Cityscapes. Is that true? Have you downloaded CS from other sources?

**Comment by ToniRV** [comment]
I diwnloaded gtFine and leftImg8bit from the official CS. But it’s up to you where you save 

The default structure is:
Would be great if you could specify that there is a structure on how cityscapes dataset is downloaded:
```
datasets/
├── gtFine
└── leftImg8bit
```
