### ISSUE TITLE
Measurement of the processing time under PyTorch

### ISSUE THREAD

**Issue by InstantWindy** [orsic/swiftnet#7]
Hi！ Do you release "Measurement of the processing time under PyTorch" Code ? I didn't find it in the repo. I want to know how you calculate the FPS。 Looking forward to your reply,Thanks!

**Comment by Rudychan** [comment]
> Hi！ Do you release "Measurement of the processing time under PyTorch" Code ? I didn't find it in the repo. I want to know how you calculate the FPS。 Looking forward to your reply,Thanks!
You can find the code in the paper 《In Defense of Pre-trained ImageNet Architecturesfor Real-time Semantic Segmentation of Road-driving Images》-- Shown in Figure5

**Comment by Rudychan** [comment]
> Hi！ Do you release "Measurement of the processing time under PyTorch" Code ? I didn't find it in the repo. I want to know how you calculate the FPS。 Looking forward to your reply,Thanks!

You can find the code in the paper 《In Defense of Pre-trained ImageNet Architecturesfor Real-time Semantic Segmentation of Road-driving Images》-- Shown in Figure5
